### ISSUE TITLE
Error!Connect bitpay

### ISSUE THREAD

**Issue by CourtierCai** [bitpay/opencart-plugin#55] opened 2018-01-26 08:42 UTC
Fatal Error: The BitPay payment extension was not installed correctly or the files are corrupt. Please reinstall the extension. If this message persists after a reinstall, contact support@bitpay.com with this message. in /alidata/www/phpwind/myshop/vqmod/vqcache/vq2-system_library_bitpay.php on line 34
Fatal error: Uncaught Error: Class 'Bitpay\PrivateKey' not found in /alidata/www/phpwind/myshop/vqmod/vqcache/vq2-system_library_bitpay.php:134 Stack trace: #0 /alidata/www/phpwind/myshop/vqmod/vqcache/vq2-system_library_bitpay.php(66): Bitpay->generateId() #1 /alidata/www/phpwind/myshop/admin/controller/extension/payment/bitpay.php(333): Bitpay->getPairingUrl() #2 /alidata/www/phpwind/myshop/vqmod/vqcache/vq2-system_storage_modification_system_engine_action.php(79): ControllerExtensionPaymentBitpay->connect() #3 /alidata/www/phpwind/myshop/admin/controller/startup/router.php(26): Action->execute(Object(Registry), Array) #4 /alidata/www/phpwind/myshop/vqmod/vqcache/vq2-system_storage_modification_system_engine_action.php(79): ControllerStartupRouter->index() #5 /alidata/www/phpwind/myshop/system/engine/router.php(67): Action->execute(Object(Registry)) #6 /alidata/www/phpwind/myshop/system/engine/router.php(56): Router->execute(Object(Action)) #7 /alidata/www/phpwind/myshop/system/framework.php(188): Router->dispatch(Objec in /alidata/www/phpwind/myshop/vqmod/vqcache/vq2-system_library_bitpay.php on line 134

**Comment by pieterpoorthuis** [comment] 2018-01-26 09:00
It looks like you're missing the BitPay PHP library.

Please make sure you installed the release (https://github.com/bitpay/opencart-plugin/releases/download/v2.2/bitpay-opencard.ocmod.zip) and not the source code.

**Comment by CourtierCai** [comment] 2018-01-26 09:02
Hi，I'm install this
https://github.com/bitpay/opencart3-plugin/releases/download/v3.0/bitpay-opencart.ocmod.zip
and sure not the source code.

2018-01-26 17:00 GMT+08:00 Pieter Poorthuis <notifications@github.com>:

**Comment by pieterpoorthuis** [comment] 2018-01-26 09:03
The release you're pointing to is for OpenCart v3.

Which version of OpenCart are you running?

**Comment by CourtierCai** [comment] 2018-01-26 09:04
Hi,The version:3.0.2.1

2018-01-26 17:03 GMT+08:00 Pieter Poorthuis <notifications@github.com>:

**Comment by CourtierCai** [comment] 2018-01-26 09:10
Hi，How to solve it? what is the missing  BitPay PHP library.

2018-01-26 17:04 GMT+08:00 蔡朝臣 <aasuperkey@gmail.com>:

**Comment by pieterpoorthuis** [comment] 2018-01-26 09:11
I'm checking what the possible cause is

**Comment by CourtierCai** [comment] 2018-01-26 09:12
and My server has the 'Bitpay\PrivateKey' in the system. Thank you 

 Uncaught Error: Class 'Bitpay\PrivateKey' not found in

**Comment by pieterpoorthuis** [comment] 2018-01-26 11:46
I've updated the release with a new directory structure. Can you download & install this version: https://github.com/bitpay/opencart3-plugin/releases/download/v3.0/bitpay-opencart.ocmod.zip

**Comment by CourtierCai** [comment] 2018-01-26 11:47
thankyou

2018年1月26日 下午7:46，"Pieter Poorthuis" <notifications@github.com>写道：

**Comment by CourtierCai** [comment] 2018-01-26 14:10
Fatal Error: The BitPay payment extension was not installed correctly or the files are corrupt. Please reinstall the extension. If this message persists after a reinstall, contact support@bitpay.com with this message. in /alidata/www/phpwind/myshop/vqmod/vqcache/vq2-system_library_bitpay.php on line 34
Fatal error: Uncaught Error: Class 'Bitpay\PrivateKey' not found in /alidata/www/phpwind/myshop/vqmod/vqcache/vq2-system_library_bitpay.php:134 Stack trace: #0 /alidata/www/phpwind/myshop/admin/controller/extension/payment/bitpay.php(539): Bitpay->generateId() #1 /alidata/www/phpwind/myshop/vqmod/vqcache/vq2-system_storage_modification_system_engine_action.php(79): ControllerExtensionPaymentBitpay->install() #2 /alidata/www/phpwind/myshop/vqmod/vqcache/vq2-system_storage_modification_system_engine_loader.php(52): Action->execute(Object(Registry), Array) #3 /alidata/www/phpwind/myshop/admin/controller/extension/extension/payment.php(27): Loader->controller('extension/payme...') #4 /alidata/www/phpwind/myshop/vqmod/vqcache/vq2-system_storage_modification_system_engine_action.php(79): ControllerExtensionExtensionPayment->install() #5 /alidata/www/phpwind/myshop/admin/controller/startup/router.php(26): Action->execute(Object(Registry), Array) #6 /alidata/www/phpwind/myshop/vqmod/vqcache/vq2-system_storage_modification_system_ in /alidata/www/phpwind/myshop/vqmod/vqcache/vq2-system_library_bitpay.php on line 134


againt

**Comment by CourtierCai** [comment] 2018-01-26 14:10
again and again

**Comment by pieterpoorthuis** [comment] 2018-01-26 14:13
I haven't been able to reproduce this error, but I'll dive deeper to find out what happens

**Comment by CourtierCai** [comment] 2018-01-26 14:14
OK。Thans

2018-01-26 22:13 GMT+08:00 Pieter Poorthuis <notifications@github.com>:

**Comment by CourtierCai** [comment] 2018-01-26 14:15
Thank you.Look forward to your reply.

2018-01-26 22:13 GMT+08:00 Pieter Poorthuis <notifications@github.com>:

**Comment by ray-moncada** [comment] 2018-02-03 23:49
I am new to the installation. After reviewing the install function. My question is do I need to manually create a private key?

**Comment by pieterpoorthuis** [comment] 2018-03-19 10:54
The issue is related to using VqMod.
Quick fix is to disable VqMod.

We are looking to fix the issue in the BitPay plugin, but I can't provide a timeline yet.

**Comment by pieterpoorthuis** [comment] 2018-03-28 14:26
Fixed in release v2.2.1

**Closed by pieterpoorthuis** 2018-03-28 14:26 UTC
